// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC81CMEJgBTfFJrexYIbhIuq7NouoIQ0xA',
    appId: '1:893039335832:web:e2a5d7470ec5a4ba1a73ed',
    messagingSenderId: '893039335832',
    projectId: 'fir-b8ec5',
    authDomain: 'fir-b8ec5.firebaseapp.com',
    storageBucket: 'fir-b8ec5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDydgjCe-vHorOqEvPaf6K4PaTbDmBn2ns',
    appId: '1:893039335832:android:93358be4922bd8931a73ed',
    messagingSenderId: '893039335832',
    projectId: 'fir-b8ec5',
    storageBucket: 'fir-b8ec5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE-ErgcowfeEq39HUi4CWysa7Qmebas0E',
    appId: '1:893039335832:ios:2d9974faed919cd61a73ed',
    messagingSenderId: '893039335832',
    projectId: 'fir-b8ec5',
    storageBucket: 'fir-b8ec5.appspot.com',
    androidClientId: '893039335832-oug9rjbnth3of6fe2qec6qvqv0oqp6n1.apps.googleusercontent.com',
    iosClientId: '893039335832-b16ho0kc1gkcn36a01e7qoh25qgupevm.apps.googleusercontent.com',
    iosBundleId: 'com.example.assigenement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE-ErgcowfeEq39HUi4CWysa7Qmebas0E',
    appId: '1:893039335832:ios:a7db71367ce4f6d11a73ed',
    messagingSenderId: '893039335832',
    projectId: 'fir-b8ec5',
    storageBucket: 'fir-b8ec5.appspot.com',
    androidClientId: '893039335832-oug9rjbnth3of6fe2qec6qvqv0oqp6n1.apps.googleusercontent.com',
    iosClientId: '893039335832-cp8osor5gjad58lqdk7d2qb1ll841cfo.apps.googleusercontent.com',
    iosBundleId: 'com.example.assigenement.RunnerTests',
  );
}
